# Generated by Django 4.2 on 2025-03-07 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom', '0002_alter_administrativepost_id_alter_aldeia_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diresaun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KartaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente', models.CharField(max_length=50)),
                ('destinatário', models.CharField(max_length=50)),
                ('no_karta', models.CharField(max_length=50, unique=True)),
                ('data_entrada', models.DateField()),
                ('data_dok', models.DateField()),
                ('no_referensia', models.CharField(blank=True, max_length=50, null=True)),
                ('assunto', models.CharField(max_length=255)),
                ('hato_o_ba', models.CharField(max_length=255)),
                ('husi', models.CharField(max_length=255)),
                ('dokumen', models.FileField(blank=True, null=True, upload_to='Arquivu/KartaSaida/')),
                ('despaixa', models.CharField(blank=True, max_length=800, null=True)),
                ('is_read', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='KartaSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_karta', models.CharField(max_length=50, unique=True)),
                ('data_saida', models.DateField()),
                ('data_dok', models.DateField()),
                ('no_referensia', models.CharField(blank=True, max_length=50, null=True)),
                ('assunto', models.CharField(max_length=255)),
                ('hato_o_ba', models.CharField(max_length=255)),
                ('husi', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-data_saida'],
            },
        ),
        migrations.CreateModel(
            name='MapaKlinik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran_klinik', models.CharField(max_length=255, unique=True)),
                ('tipo_klinik', models.CharField(choices=[('Privadu', 'Privadu'), ('Publiku', 'Publiku')], max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('data_registu', models.DateField(auto_now_add=True)),
                ('administrativepost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AAdministrativePost', to='custom.administrativepost')),
                ('aldeia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.aldeia')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MMunicipality', to='custom.municipality')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VVillage', to='custom.village')),
            ],
            options={
                'verbose_name': 'Mapa Klinik',
                'verbose_name_plural': 'Mapa Klinik',
                'ordering': ['naran_klinik'],
            },
        ),
        migrations.CreateModel(
            name='Funsionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('numero_identificacao', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('sexu', models.CharField(choices=[('Mane', 'Mane'), ('Feto', 'Feto')], default='Mane', max_length=50)),
                ('cargo', models.CharField(max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_entrada', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Funsionariu/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Leave', 'Leave'), ('Dismissed', 'Dismissed')], default='Active', max_length=50)),
                ('status_profisaun', models.CharField(choices=[('Kontratadu', 'Kontratadu'), ('Permanente', 'Permanente')], default='Permanente', max_length=50)),
                ('departamentu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArquivoRelatoriu.departamentu')),
                ('diresaun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArquivoRelatoriu.diresaun')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ClienteRaiPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='MapaKlinik/')),
                ('klinika', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinikLocation', to='ArquivoRelatoriu.mapaklinik')),
            ],
        ),
        migrations.CreateModel(
            name='ArquivuRelatoriu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_carta', models.CharField(max_length=50)),
                ('data_Arquivu', models.DateField()),
                ('titulo', models.CharField(max_length=500)),
                ('hato_o_ba', models.CharField(max_length=1000, null=True)),
                ('documento_pdf', models.FileField(upload_to='arquivu_relatoriu_pdfs/')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArquivoRelatoriu.departamentu')),
            ],
        ),
    ]
